# Homework 1

In [50]:
import pandas as pd
import numpy as np

### Q1. Pandas version
What's the version of Pandas that you installed?

You can get the version information using the `__version__` field:

In [5]:
pd.__version__

'2.2.2'

### Getting the data
For this homework, we'll use the Laptops Price dataset.

In [4]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv

df = pd.read_csv("laptops.csv")

--2024-09-18 11:57:28--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 298573 (292K) [text/plain]
Saving to: ‘laptops.csv.1’

laptops.csv.1       100%[===================>] 291.58K  --.-KB/s    in 0.03s   

2024-09-18 11:57:28 (9.20 MB/s) - ‘laptops.csv.1’ saved [298573/298573]



### Q2. Records count
How many records are in the dataset?

In [6]:
df.shape[0]

2160

### Q3. Laptop brands
How many laptop brands are presented in the dataset?

In [8]:
df.Brand.nunique()

27

### Q4. Missing values
How many columns in the dataset have missing values?

In [10]:
missing_columns = df.columns[df.isna().any()].tolist()
print(missing_columns)

['Storage type', 'GPU', 'Screen']


### Q5. Maximum final price
What's the maximum final price of Dell notebooks in the dataset?

In [14]:
df_dell = df[df["Brand"] == "Dell"]
df_dell["Final Price"].max()

3936.0

### Q6. Median value of Screen
1. Find the median value of `Screen` column in the dataset.
2. Next, calculate the most frequent value of the same `Screen` column.
3. Use `fillna` method to fill the missing values in `Screen` column with the most frequent value from the previous step.
4. Now, calculate the median value of `Screen` once again.

In [39]:
median_old = df.Screen.median()
median_old


15.6

In [36]:
most_frequent = df["Screen"].mode()[0]
most_frequent

15.6

In [43]:
df.Screen.isna().value_counts()

Screen
False    2156
True        4
Name: count, dtype: int64

In [38]:
df_filled_null = df.copy()

df_filled_null["Screen"] = df["Screen"].fillna(value=most_frequent)
df_filled_null["Screen"].isna().value_counts()

Screen
False    2160
Name: count, dtype: int64

In [42]:
median_new = df_filled_null.Screen.median()
median_new

15.6

### Q7. Sum of weights
1. Select all the "Innjoo" laptops from the dataset.
2. Select only columns `RAM`, `Storage`, `Screen`.
3. Get the underlying NumPy array. Let's call it `X`.
4. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
5. Compute the inverse of `XTX`.
6. Create an array `y` with values `[1100, 1300, 800, 900, 1000, 1100]`.
7. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
8. What's the sum of all the elements of the result?

In [ ]:
df_innjoo = df.query('''Brand=="Innjoo"''')
df_innjoo = df_innjoo[["RAM", "Storage", "Screen"]]

In [56]:
X = df_innjoo.values

XTX = X.T.dot(X)
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [53]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [52]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])

array([1100, 1300,  800,  900, 1000, 1100])

In [61]:
w = XTX_inv.dot(X.T).dot(y)

w.sum()

91.29988062995588